version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    cpu_shares: 100
    mem_limit: 256000000
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=jb80049JB
      - MYSQL_PASSWORD=jb80049JB
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:  
    image: nextcloud
    cpu_shares: 100
    mem_limit: 256000000
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
